os: windows
language: shell
env:
    - RUNTIME=wlp RUNTIME_VERSION=18.0.0.4
    - RUNTIME=wlp RUNTIME_VERSION=19.0.0.2
    - RUNTIME=ol RUNTIME_VERSION=18.0.0.4
    - RUNTIME=ol RUNTIME_VERSION=19.0.0.2
before_install:
    - cd ./travis
    - source prepare.sh
    - bash java.sh
    - bash maven.sh
    - bash installCommon.sh
    - cd ..
script:
    - export GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs='-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m'"
    - ./gradlew install check -Druntime=$RUNTIME -DruntimeVersion=$RUNTIME_VERSION --stacktrace --info -Ptest.include='**/*LooseApplication*'
dist: trusty
